spring.application.name=lesson10

# ==============================================================================
# VERİTABANI SEÇİMİ (Agnostik Yapı)
# İstediğin veritabanını kullanmak için onun altındaki satırların başındaki 
# '#' (yorum) işaretini kaldır, diğerini yoruma al. Bu kadar basit!
# ==============================================================================

# -----------------
# 1. POSTGRESQL AYARLARI (ŞU AN AKTİF OLAN)
# -----------------
spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5444}/${POSTGRES_DB:userdb}
spring.datasource.username=${POSTGRES_USER:pguser}
spring.datasource.password=${POSTGRES_PASSWORD:pgpass}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# -----------------
# 2. MYSQL AYARLARI (Eğer buna geçmek istersen üsttekileri kapat, bunları aç)
# -----------------
# spring.datasource.url=jdbc:mysql://localhost:${MYSQL_PORT:3306}/${MYSQL_DATABASE:orderdb}
# spring.datasource.username=${MYSQL_USER:mysqluser}
# spring.datasource.password=${MYSQL_PASSWORD:mysqlpass}
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ==============================================================================
# HIBERNATE ORTAK AYARLARI
# ==============================================================================
#. Gerçek projelerde veritabanı tablolarını Java'nın kafasına göre değiştirmesine izin verilmez

# Flyway veya Liquibase adını verdiğimiz özel veritabanı versiyonlama araçları kullanılır 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Ayarları
jwt.secret=${JWT_SECRET:BuBenimCokGizliVeGuvenliAnahtarimLessonSekizIcinBunuKullanacagiz}

# IYZICO Ayarları
iyzico.api-key=${IYZICO_API_KEY}
iyzico.secret-key=${IYZICO_SECRET_KEY}
iyzico.base-url=${IYZICO_BASE_URL}
iyzico.callback-url=${IYZICO_CALLBACK_URL}

# E-MAIL (SMTP) Ayarları
spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME:}
spring.mail.password=${SMTP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
